// ═══════════════════════════════════════════════════════════════
// QUOTES — add or remove entries freely; keep the format below.
// ═══════════════════════════════════════════════════════════════
if (typeof QUOTES === "undefined") var QUOTES = [
  // ── Wisdom & Life
  { text: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
  { text: "In the middle of every difficulty lies opportunity.", author: "Albert Einstein" },
  { text: "Life is what happens when you're busy making other plans.", author: "John Lennon" },
  { text: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
  { text: "It is during our darkest moments that we must focus to see the light.", author: "Aristotle" },
  { text: "The secret of getting ahead is getting started.", author: "Mark Twain" },
  { text: "You miss 100% of the shots you don't take.", author: "Wayne Gretzky" },
  { text: "Whether you think you can or you can't, you're right.", author: "Henry Ford" },
  { text: "I have not failed. I've just found 10,000 ways that won't work.", author: "Thomas Edison" },
  { text: "The mind is everything. What you think you become.", author: "Buddha" },
  { text: "The journey of a thousand miles begins with one step.", author: "Lao Tzu" },
  { text: "That which does not kill us makes us stronger.", author: "Friedrich Nietzsche" },
  { text: "Be yourself; everyone else is already taken.", author: "Oscar Wilde" },
  { text: "Be the change you wish to see in the world.", author: "Mahatma Gandhi" },
  { text: "Imagination is more important than knowledge.", author: "Albert Einstein" },
  { text: "An unexamined life is not worth living.", author: "Socrates" },
  { text: "Life is short, and it is here to be lived.", author: "Kate Winslet" },
  { text: "Turn your wounds into wisdom.", author: "Oprah Winfrey" },
  { text: "We are what we repeatedly do.", author: "Aristotle" },
  { text: "Do one thing every day that scares you.", author: "Eleanor Roosevelt" },
  { text: "Well done is better than well said.", author: "Benjamin Franklin" },
  { text: "In the end, it's not the years in your life that count.", author: "Abraham Lincoln" },
  { text: "Never let the fear of striking out keep you from playing the game.", author: "Babe Ruth" },
  { text: "Life is either a daring adventure or nothing at all.", author: "Helen Keller" },
  { text: "You only live once, but if you do it right, once is enough.", author: "Mae West" },
  { text: "The only impossible journey is the one you never begin.", author: "Tony Robbins" },
  { text: "It always seems impossible until it's done.", author: "Nelson Mandela" },
  { text: "Don't count the days, make the days count.", author: "Muhammad Ali" },
  { text: "You don't have to be great to start, but you have to start to be great.", author: "Zig Ziglar" },
  { text: "Everything you've ever wanted is on the other side of fear.", author: "George Addair" },
  { text: "Success is not final, failure is not fatal: courage is what counts.", author: "Winston Churchill" },
  { text: "Strive not to be a success, but rather to be of value.", author: "Albert Einstein" },
  { text: "The best time to plant a tree was 20 years ago. The second best time is now.", author: "Chinese Proverb" },
  { text: "Two roads diverged in a wood, and I took the one less traveled.", author: "Robert Frost" },
  { text: "In three words: it goes on.", author: "Robert Frost" },
  { text: "We must accept finite disappointment, but never lose infinite hope.", author: "Martin Luther King Jr." },
  { text: "What you do today can improve all your tomorrows.", author: "Ralph Marston" },
  { text: "Act as if what you do makes a difference. It does.", author: "William James" },
  { text: "The purpose of our lives is to be happy.", author: "Dalai Lama" },
  { text: "Life is not measured by the number of breaths we take.", author: "Maya Angelou" },
  { text: "If opportunity doesn't knock, build a door.", author: "Milton Berle" },
  { text: "The best revenge is massive success.", author: "Frank Sinatra" },
  { text: "When everything seems to be going against you, remember that the airplane takes off against the wind.", author: "Henry Ford" },
  { text: "I find that the harder I work, the more luck I seem to have.", author: "Thomas Jefferson" },
  { text: "Eighty percent of success is showing up.", author: "Woody Allen" },
  { text: "A person who never made a mistake never tried anything new.", author: "Albert Einstein" },
  { text: "Dream big and dare to fail.", author: "Norman Vaughan" },
  { text: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius" },
  { text: "Our greatest glory is not in never falling, but in rising every time we fall.", author: "Confucius" },
  { text: "You were born to win, but to be a winner, you must plan, prepare, and expect to win.", author: "Zig Ziglar" },
  { text: "The harder the conflict, the more glorious the triumph.", author: "Thomas Paine" },
  // ── Courage & Action
  { text: "Courage is not the absence of fear, but acting in spite of it.", author: "Mark Twain" },
  { text: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe" },
  { text: "Don't wish it were easier; wish you were better.", author: "Jim Rohn" },
  { text: "Either you run the day or the day runs you.", author: "Jim Rohn" },
  { text: "Motivation is what gets you started. Habit is what keeps you going.", author: "Jim Ryun" },
  { text: "Little things make big days.", author: "Unknown" },
  { text: "It's hard to beat a person who never gives up.", author: "Babe Ruth" },
  { text: "I wake up every morning and think to myself: how far can I push this company in the next 24 hours.", author: "Leah Busque" },
  { text: "If you're offered a seat on a rocket ship, don't ask what seat! Just get on.", author: "Sheryl Sandberg" },
  { text: "I attribute my success to this: I never gave or took any excuse.", author: "Florence Nightingale" },
  { text: "You only fail when you stop trying.", author: "Unknown" },
  { text: "The secret of success is to do the common thing uncommonly well.", author: "John D. Rockefeller Jr." },
  { text: "I didn't fail the test. I just found 100 ways to do it wrong.", author: "Benjamin Franklin" },
  { text: "If you do what you always did, you will get what you always got.", author: "Albert Einstein" },
  { text: "Knowing is not enough; we must apply. Willing is not enough; we must do.", author: "Johann Wolfgang von Goethe" },
  { text: "Skill is only developed by hours and hours of work.", author: "Usain Bolt" },
  { text: "Be brave. Take risks. Nothing can substitute experience.", author: "Paulo Coelho" },
  { text: "I have stood on a mountain of no's to get to a yes.", author: "B. Smith" },
  { text: "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.", author: "Roy T. Bennett" },
  { text: "The more that you read, the more things you will know.", author: "Dr. Seuss" },
  { text: "You get what you give.", author: "Jennifer Lopez" },
  { text: "Dream as if you'll live forever, live as if you'll die today.", author: "James Dean" },
  { text: "I can and I will. Watch me.", author: "Unknown" },
  { text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
  { text: "The way to get started is to quit talking and begin doing.", author: "Walt Disney" },
  { text: "It's not whether you get knocked down, it's whether you get up.", author: "Vince Lombardi" },
  { text: "Change your thoughts and you change your world.", author: "Norman Vincent Peale" },
  { text: "Don't let yesterday take up too much of today.", author: "Will Rogers" },
  { text: "You learn more from failure than from success.", author: "Unknown" },
  { text: "We generate fears while we sit. We overcome them by action.", author: "Dr. Henry Link" },
  { text: "Whether you think you can or think you can't, you're right.", author: "Henry Ford" },
  { text: "Security is mostly a superstition. Life is either a daring adventure or nothing.", author: "Helen Keller" },
  // ── Happiness & Gratitude
  { text: "Happiness is not something ready made. It comes from your own actions.", author: "Dalai Lama" },
  { text: "Spread love everywhere you go.", author: "Mother Teresa" },
  { text: "When you reach the end of your rope, tie a knot in it and hang on.", author: "Franklin D. Roosevelt" },
  { text: "Always remember that you are absolutely unique. Just like everyone else.", author: "Margaret Mead" },
  { text: "Don't judge each day by the harvest you reap but by the seeds that you plant.", author: "Robert Louis Stevenson" },
  { text: "The best way to cheer yourself is to try to cheer someone else up.", author: "Mark Twain" },
  { text: "Happiness is when what you think, what you say, and what you do are in harmony.", author: "Mahatma Gandhi" },
  { text: "Dwell on the beauty of life. Watch the stars, and see yourself running with them.", author: "Marcus Aurelius" },
  { text: "If you want to live a happy life, tie it to a goal, not to people or things.", author: "Albert Einstein" },
  { text: "The two most important days in your life are the day you were born and the day you find out why.", author: "Mark Twain" },
  { text: "He who is not courageous enough to take risks will accomplish nothing in life.", author: "Muhammad Ali" },
  { text: "Gratitude is not only the greatest of virtues, but the parent of all others.", author: "Cicero" },
  { text: "Even if you're on the right track, you'll get run over if you just sit there.", author: "Will Rogers" },
  { text: "A truly rich man is one whose children run into his arms when his hands are empty.", author: "Unknown" },
  { text: "You must be the change you wish to see in the world.", author: "Mahatma Gandhi" },
  { text: "Not how long, but how well you have lived is the main thing.", author: "Seneca" },
  { text: "You only live once, but if you do it right, once is enough.", author: "Mae West" },
  { text: "In order to write about life first you must live it.", author: "Ernest Hemingway" },
  { text: "It's not what you look at that matters, it's what you see.", author: "Henry David Thoreau" },
  { text: "Nothing is impossible, the word itself says 'I'm possible'!", author: "Audrey Hepburn" },
  // ── Creativity & Thinking
  { text: "Logic will get you from A to Z; imagination will get you everywhere.", author: "Albert Einstein" },
  { text: "The best way to predict your future is to create it.", author: "Abraham Lincoln" },
  { text: "Do not go where the path may lead; go where there is no path and leave a trail.", author: "Ralph Waldo Emerson" },
  { text: "Live as if you were to die tomorrow. Learn as if you were to live forever.", author: "Mahatma Gandhi" },
  { text: "The mind is everything. What you think you become.", author: "Buddha" },
  { text: "Every artist was first an amateur.", author: "Ralph Waldo Emerson" },
  { text: "It is never too late to be what you might have been.", author: "George Eliot" },
  { text: "You can never cross the ocean until you have the courage to lose sight of the shore.", author: "Christopher Columbus" },
  { text: "Either write something worth reading or do something worth writing.", author: "Benjamin Franklin" },
  { text: "Innovation distinguishes between a leader and a follower.", author: "Steve Jobs" },
  { text: "Great minds discuss ideas; small minds discuss people.", author: "Eleanor Roosevelt" },
  { text: "If you tell the truth, you don't have to remember anything.", author: "Mark Twain" },
  { text: "A room without books is like a body without a soul.", author: "Marcus Tullius Cicero" },
  { text: "You can never be overdressed or overeducated.", author: "Oscar Wilde" },
  { text: "Simplicity is the ultimate sophistication.", author: "Leonardo da Vinci" },
  { text: "I have a dream.", author: "Martin Luther King Jr." },
  { text: "Ask not what your country can do for you, ask what you can do for your country.", author: "John F. Kennedy" },
  { text: "The greatest glory in living lies not in never falling, but in rising every time we fall.", author: "Nelson Mandela" },
  { text: "When one door of happiness closes, another opens.", author: "Helen Keller" },
  { text: "The real test is not whether you avoid failure, it's whether you learn from it.", author: "Barack Obama" },
  // ── Stoic & Philosophy
  { text: "You have power over your mind, not outside events.", author: "Marcus Aurelius" },
  { text: "Waste no more time arguing about what a good man should be. Be one.", author: "Marcus Aurelius" },
  { text: "The happiness of your life depends upon the quality of your thoughts.", author: "Marcus Aurelius" },
  { text: "Very little is needed to make a happy life; it is all within yourself.", author: "Marcus Aurelius" },
  { text: "If it is not right, do not do it; if it is not true, do not say it.", author: "Marcus Aurelius" },
  { text: "Begin at once to live, and count each separate day as a separate life.", author: "Seneca" },
  { text: "Luck is what happens when preparation meets opportunity.", author: "Seneca" },
  { text: "We suffer more in imagination than in reality.", author: "Seneca" },
  { text: "It is not that I'm so smart. It's just that I stay with problems longer.", author: "Albert Einstein" },
  { text: "Know thyself.", author: "Socrates" },
  { text: "The unexamined life is not worth living.", author: "Socrates" },
  { text: "Educating the mind without educating the heart is no education at all.", author: "Aristotle" },
  { text: "We are what we repeatedly do. Excellence, then, is not an act, but a habit.", author: "Aristotle" },
  { text: "He who conquers himself is the mightiest warrior.", author: "Confucius" },
  { text: "Real knowledge is to know the extent of one's ignorance.", author: "Confucius" },
  { text: "Life is really simple, but we insist on making it complicated.", author: "Confucius" },
  { text: "The man who moves a mountain begins by carrying away small stones.", author: "Confucius" },
  { text: "To know what you know and what you do not know, that is true knowledge.", author: "Confucius" },
  { text: "Do not pray for easy lives. Pray to be stronger men.", author: "John F. Kennedy" },
  { text: "A fool thinks himself to be wise, but a wise man knows himself to be a fool.", author: "William Shakespeare" },
  { text: "All that we see or seem is but a dream within a dream.", author: "Edgar Allan Poe" },
  { text: "Not all those who wander are lost.", author: "J.R.R. Tolkien" },
  { text: "Even the darkest night will end and the sun will rise.", author: "Victor Hugo" },
  { text: "There is no greater agony than bearing an untold story inside you.", author: "Maya Angelou" },
  { text: "If you want to know what a man's like, take a good look at how he treats his inferiors.", author: "J.K. Rowling" },
  { text: "It matters not what someone is born, but what they grow to be.", author: "J.K. Rowling" },
  { text: "Words are our most inexhaustible source of magic.", author: "J.K. Rowling" },
  { text: "To the well-organized mind, death is but the next great adventure.", author: "J.K. Rowling" },
  // ── Growth & Resilience
  { text: "Fall seven times, stand up eight.", author: "Japanese Proverb" },
  { text: "What we fear doing most is usually what we most need to do.", author: "Tim Ferriss" },
  { text: "A ship in harbour is safe, but that is not what ships are built for.", author: "John A. Shedd" },
  { text: "Done is better than perfect.", author: "Sheryl Sandberg" },
  { text: "Whatever you are, be a good one.", author: "Abraham Lincoln" },
  { text: "You will never always be motivated, so you must learn to be disciplined.", author: "Unknown" },
  { text: "Progress, not perfection.", author: "Unknown" },
  { text: "Small steps every day.", author: "Unknown" },
  { text: "You are enough, just as you are.", author: "Meghan Markle" },
  { text: "The secret is to work less as individuals and more as a team.", author: "Knute Rockne" },
  { text: "The strength of the team is each individual member.", author: "Phil Jackson" },
  { text: "Talent wins games, but teamwork wins championships.", author: "Michael Jordan" },
  { text: "I've missed more than 9000 shots. That's why I succeed.", author: "Michael Jordan" },
  { text: "Limits, like fears, are often just an illusion.", author: "Michael Jordan" },
  { text: "Winning means you're willing to go longer, work harder, and give more than anyone else.", author: "Vince Lombardi" },
  { text: "The more I practice, the luckier I get.", author: "Gary Player" },
  { text: "Success comes from knowing that you did your best.", author: "Brian Zahnd" },
  { text: "Champions keep playing until they get it right.", author: "Billie Jean King" },
  { text: "Do what you can, with what you have, where you are.", author: "Theodore Roosevelt" },
  { text: "Believe deep down in your heart that you're destined to do great things.", author: "Joe Paterno" },
  // ── Short & Punchy
  { text: "Less is more.", author: "Ludwig Mies van der Rohe" },
  { text: "Stay hungry. Stay foolish.", author: "Steve Jobs" },
  { text: "Just do it.", author: "Nike" },
  { text: "Think different.", author: "Apple" },
  { text: "Make it work.", author: "Tim Gunn" },
  { text: "Create the life you can't wait to wake up to.", author: "Unknown" },
  { text: "Do more of what makes you happy.", author: "Unknown" },
  { text: "Choose kindness.", author: "Unknown" },
  { text: "Be the light.", author: "Unknown" },
  { text: "Work hard in silence; let success be the noise.", author: "Frank Ocean" },
  { text: "Be so good they can't ignore you.", author: "Steve Martin" },
  { text: "Actions speak louder than words.", author: "Unknown" },
  { text: "Clarity is power.", author: "Unknown" },
  { text: "Less talk, more action.", author: "Unknown" },
  { text: "Energy is everything.", author: "Unknown" },
  { text: "Chase excellence, success will follow.", author: "Rancho, 3 Idiots" },
  { text: "Make today count.", author: "Unknown" },
  { text: "Now or never.", author: "Unknown" },
  { text: "Earn it.", author: "Unknown" },
  { text: "One day or day one. You decide.", author: "Unknown" },
  { text: "Be relentless.", author: "Unknown" },
  { text: "You've got this.", author: "Unknown" },
  { text: "Build something you're proud of.", author: "Unknown" },
  { text: "Stay consistent.", author: "Unknown" },
  { text: "Commit to the process.", author: "Unknown" },
  { text: "Results don't lie.", author: "Unknown" },
  { text: "Make the most of yourself, for that is all there is of you.", author: "Ralph Waldo Emerson" },
  { text: "Push yourself, because no one else is going to do it for you.", author: "Unknown" },
  { text: "Great things never come from comfort zones.", author: "Unknown" },
  { text: "Dream it. Wish it. Do it.", author: "Unknown" },
  { text: "Success doesn't just find you. You have to go out and get it.", author: "Unknown" },
  { text: "The harder you work for something, the greater you'll feel when you achieve it.", author: "Unknown" },
  { text: "Dream bigger. Do bigger.", author: "Unknown" },
  { text: "Don't stop when you're tired. Stop when you're done.", author: "Unknown" },
  { text: "Wake up with determination. Go to bed with satisfaction.", author: "Unknown" },
  { text: "Do something today that your future self will thank you for.", author: "Unknown" },
  { text: "Little by little, a little becomes a lot.", author: "Tanzanian Proverb" },
  { text: "You don't get what you wish for. You get what you work for.", author: "Unknown" },
  { text: "Be stronger than your excuses.", author: "Unknown" },
  { text: "Difficult roads often lead to beautiful destinations.", author: "Unknown" },
  { text: "Stay patient and trust your journey.", author: "Unknown" },
  { text: "Focus on the good.", author: "Unknown" },
  { text: "The key is to keep company only with people who uplift you.", author: "Epictetus" },
  // ── Science & Curiosity
  { text: "The important thing is not to stop questioning.", author: "Albert Einstein" },
  { text: "Science is not only a disciple of reason but also one of romance and passion.", author: "Stephen Hawking" },
  { text: "Look up at the stars and not down at your feet.", author: "Stephen Hawking" },
  { text: "The greatest enemy of knowledge is not ignorance; it is the illusion of knowledge.", author: "Stephen Hawking" },
  { text: "We are all connected; to each other, biologically. To the earth, chemically. To the rest of the universe, atomically.", author: "Neil deGrasse Tyson" },
  { text: "For small creatures such as we, the vastness is bearable only through love.", author: "Carl Sagan" },
  { text: "Somewhere, something incredible is waiting to be known.", author: "Carl Sagan" },
  { text: "The cosmos is within us. We are made of star-stuff.", author: "Carl Sagan" },
  { text: "Science is a way of thinking much more than it is a body of knowledge.", author: "Carl Sagan" },
  { text: "The good thing about science is that it's true whether or not you believe in it.", author: "Neil deGrasse Tyson" },
  { text: "Once you eliminate the impossible, whatever remains must be the truth.", author: "Arthur Conan Doyle" },
  { text: "I am not afraid of an army of lions led by a sheep; I am afraid of an army of sheep led by a lion.", author: "Alexander the Great" },
  // ── Technology & Future
  { text: "The advance of technology is based on making it fit in so that you don't really even notice it.", author: "Bill Gates" },
  { text: "The computer was born to solve problems that did not exist before.", author: "Bill Gates" },
  { text: "Success today requires the agility and drive to constantly rethink, reinvigorate, react, and reinvent.", author: "Bill Gates" },
  { text: "It's fine to celebrate success but it is more important to heed the lessons of failure.", author: "Bill Gates" },
  { text: "I think it's important to reason from first principles rather than by analogy.", author: "Elon Musk" },
  { text: "Failure is an option here. If things are not failing, you are not innovating enough.", author: "Elon Musk" },
  { text: "When something is important enough, you do it even if the odds are not in your favour.", author: "Elon Musk" },
  { text: "Move fast and break things.", author: "Mark Zuckerberg" },
  { text: "The biggest risk is not taking any risk.", author: "Mark Zuckerberg" },
  { text: "Stay hungry, stay humble.", author: "Unknown" },
  // ── Nature & Time
  { text: "Nature does not hurry, yet everything is accomplished.", author: "Lao Tzu" },
  { text: "In every walk with nature, one receives far more than he seeks.", author: "John Muir" },
  { text: "The earth has music for those who listen.", author: "George Santayana" },
  { text: "Look deep into nature, and then you will understand everything better.", author: "Albert Einstein" },
  { text: "To plant a garden is to believe in tomorrow.", author: "Audrey Hepburn" },
  { text: "Time is the most valuable thing a man can spend.", author: "Theophrastus" },
  { text: "Time flies over us, but leaves its shadow behind.", author: "Nathaniel Hawthorne" },
  { text: "Yesterday is history, tomorrow is a mystery, today is a gift.", author: "Alice Morse Earle" },
  { text: "The best time for new beginnings is now.", author: "Unknown" },
  { text: "Seasons change, and so do you.", author: "Unknown" },
  // ── Relationships & Kindness
  { text: "No act of kindness, no matter how small, is ever wasted.", author: "Aesop" },
  { text: "Kindness is a language which the deaf can hear and the blind can see.", author: "Mark Twain" },
  { text: "We rise by lifting others.", author: "Robert Ingersoll" },
  { text: "A friend is someone who gives you total freedom to be yourself.", author: "Jim Morrison" },
  { text: "A real friend is one who walks in when the rest of the world walks out.", author: "Walter Winchell" },
  { text: "Love is not only something you feel, it is something you do.", author: "David Wilkerson" },
  { text: "The best thing to hold onto in life is each other.", author: "Audrey Hepburn" },
  { text: "You don't love someone for their looks or their clothes or for their fancy car. You love them because they sing a song only you can hear.", author: "Oscar Wilde" },
  { text: "The most important thing in the world is family and love.", author: "John Wooden" },
  { text: "Where there is love there is life.", author: "Mahatma Gandhi" },
  { text: "The greatest thing you'll ever learn is just to love and be loved in return.", author: "eden ahbez" },
  { text: "Let us always meet each other with a smile, for the smile is the beginning of love.", author: "Mother Teresa" },
  { text: "Love all, trust a few, do wrong to none.", author: "William Shakespeare" },
  { text: "The only way to have a friend is to be one.", author: "Ralph Waldo Emerson" },
  { text: "In the end, the love you take is equal to the love you make.", author: "Paul McCartney" },
  // ── Work & Discipline
  { text: "Genius is one percent inspiration and ninety-nine percent perspiration.", author: "Thomas Edison" },
  { text: "There are no shortcuts to any place worth going.", author: "Beverly Sills" },
  { text: "Opportunity is missed by most people because it is dressed in overalls and looks like work.", author: "Thomas Edison" },
  { text: "I'm a great believer in luck, and I find the harder I work the more I have of it.", author: "Thomas Jefferson" },
  { text: "The only place where success comes before work is in the dictionary.", author: "Vidal Sassoon" },
  { text: "Perseverance is not a long race; it is many short races one after the other.", author: "Walter Elliot" },
  { text: "The man who can drive himself further once the effort gets painful is the man who will win.", author: "Roger Bannister" },
  { text: "A goal without a plan is just a wish.", author: "Antoine de Saint-Exupéry" },
  { text: "I never dreamed about success. I worked for it.", author: "Estée Lauder" },
  { text: "If you genuinely want something, don't wait for it — teach yourself to be impatient.", author: "Gurbaksh Chahal" },
  { text: "Success is walking from failure to failure with no loss of enthusiasm.", author: "Winston Churchill" },
  { text: "The secret of success is to know something nobody else knows.", author: "Aristotle Onassis" },
  { text: "If you can dream it, you can do it.", author: "Walt Disney" },
  { text: "The key to success is to focus on goals, not obstacles.", author: "Unknown" },
  { text: "Productivity is never an accident. It is the result of a commitment to excellence.", author: "Paul J. Meyer" },
  // ── Mindset
  { text: "Your attitude, not your aptitude, will determine your altitude.", author: "Zig Ziglar" },
  { text: "The only way to achieve the impossible is to believe it is possible.", author: "Charles Kingsleigh" },
  { text: "Don't limit your challenges; challenge your limits.", author: "Jerry Dunn" },
  { text: "Don't be afraid to give up the good to go for the great.", author: "John D. Rockefeller" },
  { text: "I can't change the direction of the wind, but I can adjust my sails.", author: "Jimmy Dean" },
  { text: "If you are not willing to risk the usual, you will have to settle for the ordinary.", author: "Jim Rohn" },
  { text: "Trust yourself. You know more than you think you do.", author: "Benjamin Spock" },
  { text: "Quality is not an act, it is a habit.", author: "Aristotle" },
  { text: "A mind that is stretched by a new experience can never go back to its old dimensions.", author: "Oliver Wendell Holmes Jr." },
  { text: "The best gift you can give is your honest self.", author: "Unknown" },
  { text: "Your value does not decrease based on someone's inability to see your worth.", author: "Unknown" },
  { text: "Believe in yourself and all that you are.", author: "Christian D. Larson" },
  { text: "Stop being afraid of what could go wrong and think of what could go right.", author: "Unknown" },
  { text: "The question isn't who's going to let me; it's who's going to stop me.", author: "Ayn Rand" },
  { text: "I can accept failure, everyone fails at something. But I can't accept not trying.", author: "Michael Jordan" },
  { text: "I don't regret the things I've done. I regret the things I didn't do when I had the chance.", author: "Unknown" },
  { text: "One small positive thought in the morning can change your whole day.", author: "Unknown" },
  { text: "The groundwork of all happiness is health.", author: "Leigh Hunt" },
  { text: "Take care of your body. It's the only place you have to live.", author: "Jim Rohn" },
  { text: "A healthy mind in a healthy body.", author: "Juvenal" },
  // ── Art & Expression
  { text: "Art is not what you see, but what you make others see.", author: "Edgar Degas" },
  { text: "Creativity takes courage.", author: "Henri Matisse" },
  { text: "The purpose of art is washing the dust of daily life off our souls.", author: "Pablo Picasso" },
  { text: "Every child is an artist. The problem is how to remain an artist once we grow up.", author: "Pablo Picasso" },
  { text: "I dream my painting and then I paint my dream.", author: "Vincent van Gogh" },
  { text: "Art enables us to find ourselves and lose ourselves at the same time.", author: "Thomas Merton" },
  { text: "The job of the artist is always to deepen the mystery.", author: "Francis Bacon" },
  { text: "Great art picks up where nature ends.", author: "Marc Chagall" },
  { text: "Music can change the world because it can change people.", author: "Bono" },
  { text: "One good thing about music, when it hits you, you feel no pain.", author: "Bob Marley" },
  { text: "Where words fail, music speaks.", author: "Hans Christian Andersen" },
  { text: "Poetry is what gets lost in translation.", author: "Robert Frost" },
  { text: "There is no greater agony than bearing an untold story inside you.", author: "Maya Angelou" },
  { text: "If you don't have time to read, you don't have time to write.", author: "Stephen King" },
  { text: "Writing is the painting of the voice.", author: "Voltaire" },
  { text: "A word after a word after a word is power.", author: "Margaret Atwood" },
  { text: "Fill your paper with the breathings of your heart.", author: "William Wordsworth" },
  { text: "Books are a uniquely portable magic.", author: "Stephen King" },
  { text: "Not all readers are leaders, but all leaders are readers.", author: "Harry S Truman" },
  // ── Morning & Daily
  { text: "Today is a good day to have a good day.", author: "Unknown" },
  { text: "Every morning you have two choices: continue to sleep with your dreams, or wake up and chase them.", author: "Unknown" },
  { text: "This is your moment. Own it.", author: "Unknown" },
  { text: "Start each day with a grateful heart.", author: "Unknown" },
  { text: "Make today amazing.", author: "Unknown" },
  { text: "New day, new chances.", author: "Unknown" },
  { text: "Rise up, start fresh, see the bright opportunity in each new day.", author: "Unknown" },
  { text: "Good morning. You've survived 100% of your worst days.", author: "Unknown" },
  { text: "Today's the day.", author: "Unknown" },
  { text: "Be happy. It drives people crazy.", author: "Unknown" },
  { text: "Your future is created by what you do today, not tomorrow.", author: "Robert Kiyosaki" },
  { text: "Don't let the perfect be the enemy of the good.", author: "Voltaire" },
  { text: "Real generosity toward the future lies in giving all to the present.", author: "Albert Camus" },
  { text: "You must expect great things of yourself before you can do them.", author: "Michael Jordan" },
  { text: "Start with why.", author: "Simon Sinek" },
  { text: "Find your tribe. Love them hard.", author: "Unknown" },
  { text: "Be you. Do you. For you.", author: "Unknown" },
  { text: "Build the life you want to live.", author: "Unknown" },
  { text: "Live. Laugh. Create.", author: "Unknown" },
  { text: "Create the life you can't wait to wake up to.", author: "Unknown" },
  { text: "Every day is a second chance.", author: "Unknown" },
  { text: "Keep going. You're closer than you think.", author: "Unknown" },
  { text: "Turn your can'ts into cans and your dreams into plans.", author: "Unknown" },
  { text: "Don't be pushed by your problems. Be led by your dreams.", author: "Ralph Waldo Emerson" },
  { text: "A ship in the harbour is safe, but that is not what ships are for.", author: "William G.T. Shedd" },
  { text: "Don't watch the clock; do what it does. Keep going.", author: "Sam Levenson" },
  { text: "There are two ways to live your life. One is as though nothing is a miracle.", author: "Albert Einstein" },
  { text: "Yesterday is not ours to recover, but tomorrow is ours to win or lose.", author: "Lyndon B. Johnson" },
  { text: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis" },
  { text: "The meaning of life is to find your gift. The purpose is to give it away.", author: "Pablo Picasso" },
  { text: "What we think, we become.", author: "Buddha" },
  { text: "With the new day comes new strength and new thoughts.", author: "Eleanor Roosevelt" },
  { text: "The only limit to our realization of tomorrow will be our doubts of today.", author: "Franklin D. Roosevelt" },
  { text: "It is always the simple that produces the marvellous.", author: "Amelia Barr" },
  { text: "You are braver than you believe, stronger than you seem, and smarter than you think.", author: "A.A. Milne" },
  { text: "Everything you can imagine is real.", author: "Pablo Picasso" },
  { text: "What you get by achieving your goals is not as important as what you become.", author: "Zig Ziglar" },
  { text: "Strength does not come from winning. Your struggles develop your strengths.", author: "Arnold Schwarzenegger" },
  { text: "Perseverance is failing 19 times and succeeding the 20th.", author: "Julie Andrews" },
  { text: "If you look at what you have in life, you'll always have more.", author: "Oprah Winfrey" },
  { text: "You will face many defeats in life, but never let yourself be defeated.", author: "Maya Angelou" },
  { text: "The most common way people give up their power is by thinking they don't have any.", author: "Alice Walker" },
  { text: "You may not control all the events that happen to you, but you can decide not to be reduced by them.", author: "Maya Angelou" },
  { text: "My mission in life is not merely to survive, but to thrive.", author: "Maya Angelou" },
  { text: "You can't use up creativity. The more you use, the more you have.", author: "Maya Angelou" },
  { text: "If you don't like something, change it. If you can't change it, change your attitude.", author: "Maya Angelou" },
  { text: "Nothing will work unless you do.", author: "Maya Angelou" },
  { text: "Courage is the most important of all the virtues because without courage, you can't practice any other virtue consistently.", author: "Maya Angelou" },
  { text: "I've learned that people will forget what you said, people will forget what you did, but people will never forget how you made them feel.", author: "Maya Angelou" },
  { text: "We delight in the beauty of the butterfly, but rarely admit the changes it has gone through to achieve that beauty.", author: "Maya Angelou" },
  { text: "One isn't necessarily born with courage, but one is born with potential.", author: "Maya Angelou" },
  { text: "There is no use trying; said Alice. One can't believe impossible things. I daresay you haven't had much practice, said the Queen.", author: "Lewis Carroll" },
  { text: "It takes courage to grow up and become who you really are.", author: "E.E. Cummings" },
  { text: "Once we accept our limits, we go beyond them.", author: "Albert Einstein" },
  { text: "Only those who dare to fail greatly can ever achieve greatly.", author: "Robert F. Kennedy" },
  { text: "In the middle of difficulty lies opportunity.", author: "Albert Einstein" },
  { text: "If you want to lift yourself up, lift up someone else.", author: "Booker T. Washington" },
  { text: "I am not a product of my circumstances. I am a product of my decisions.", author: "Stephen Covey" },
  { text: "You can never cross the ocean until you have the courage to lose sight of the shore.", author: "Christopher Columbus" },
  { text: "I've learned that making a living is not the same as making a life.", author: "Maya Angelou" },
  { text: "I attribute my success to this: I never gave or took any excuse.", author: "Florence Nightingale" },
  { text: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius" },
  { text: "When everything seems to be going against you, remember that the airplane takes off against the wind.", author: "Henry Ford" },
  { text: "Too many of us are not living our dreams because we are living our fears.", author: "Les Brown" },
  { text: "Life is 10% what happens to me and 90% how I react to it.", author: "Charles R. Swindoll" },
  { text: "Well-behaved women seldom make history.", author: "Laurel Thatcher Ulrich" },
  { text: "You must do the things you think you cannot do.", author: "Eleanor Roosevelt" },
  { text: "Accept the challenges so that you can feel the exhilaration of victory.", author: "George S. Patton" },
  { text: "To know what you know and what you do not know, that is true knowledge.", author: "Confucius" },
  { text: "I would rather die of passion than of boredom.", author: "Vincent van Gogh" },
  { text: "I am not afraid of storms, for I am learning how to sail my ship.", author: "Louisa May Alcott" },
  { text: "Don't cry because it's over, smile because it happened.", author: "Dr. Seuss" },
  { text: "In the end, we only regret the chances we didn't take.", author: "Lewis Carroll" },
  { text: "You have brains in your head and feet in your shoes. You can steer yourself in any direction you choose.", author: "Dr. Seuss" },
  { text: "Today you are You, that is truer than true. There is no one alive who is Youer than You.", author: "Dr. Seuss" },
  { text: "The more that you read, the more things you will know. The more that you learn, the more places you'll go.", author: "Dr. Seuss" },
  { text: "Sometimes you will never know the value of a moment until it becomes a memory.", author: "Dr. Seuss" },
  { text: "Unless someone like you cares a whole awful lot, nothing is going to get better. It's not.", author: "Dr. Seuss" },
,
  // ── More Wisdom ──
  { text: "The secret of change is to focus all your energy not on fighting the old, but on building the new.", author: "Socrates" },
  { text: "If you want to go fast, go alone. If you want to go far, go together.", author: "African Proverb" },
  { text: "Comparison is the thief of joy.", author: "Theodore Roosevelt" },
  { text: "Be yourself; everyone else is already taken.", author: "Oscar Wilde" },
  { text: "We are all in the gutter, but some of us are looking at the stars.", author: "Oscar Wilde" },
  { text: "I can resist everything except temptation.", author: "Oscar Wilde" },
  { text: "Always forgive your enemies; nothing annoys them so much.", author: "Oscar Wilde" },
  { text: "The world is a stage, but the play is badly cast.", author: "Oscar Wilde" },
  { text: "Experience is the name everyone gives to their mistakes.", author: "Oscar Wilde" },
  { text: "Life is too important to be taken seriously.", author: "Oscar Wilde" },
  { text: "Be careful about reading health books. You may die of a misprint.", author: "Mark Twain" },
  { text: "Age is an issue of mind over matter. If you don't mind, it doesn't matter.", author: "Mark Twain" },
  { text: "Truth is stranger than fiction, but it is because fiction is obliged to stick to possibilities.", author: "Mark Twain" },
  { text: "It is easier to fool people than to convince them that they have been fooled.", author: "Mark Twain" },
  { text: "Never miss a good chance to shut up.", author: "Will Rogers" },
  { text: "If stupidity got us into this mess, then why can't it get us out?", author: "Will Rogers" },
  { text: "Too much of a good thing can be wonderful.", author: "Mae West" },
  { text: "An optimist sees the opportunity in every difficulty.", author: "Winston Churchill" },
  { text: "If you're going through hell, keep going.", author: "Winston Churchill" },
  { text: "Success consists of going from failure to failure without loss of enthusiasm.", author: "Winston Churchill" },
  { text: "We make a living by what we get. We make a life by what we give.", author: "Winston Churchill" },
  { text: "Attitude is a little thing that makes a big difference.", author: "Winston Churchill" },
  { text: "The pessimist sees difficulty in every opportunity; the optimist sees opportunity in every difficulty.", author: "Winston Churchill" },
  { text: "I may be drunk, Miss, but in the morning I will be sober and you will still be ugly.", author: "Winston Churchill" },
  { text: "History will be kind to me for I intend to write it.", author: "Winston Churchill" },
  { text: "A lie gets halfway around the world before the truth has a chance to get its pants on.", author: "Winston Churchill" },
  { text: "Courage is what it takes to stand up and speak; courage is also what it takes to sit down and listen.", author: "Winston Churchill" },
  { text: "The truth is rarely pure and never simple.", author: "Oscar Wilde" },
  { text: "Man is not the creature of circumstances, circumstances are the creatures of men.", author: "Benjamin Disraeli" },
  { text: "We are what we pretend to be, so we must be careful about what we pretend to be.", author: "Kurt Vonnegut" },
  { text: "I tell you, we are here on Earth to fart around, and don't let anybody tell you different.", author: "Kurt Vonnegut" },
  { text: "We have to continually be jumping off cliffs and developing our wings on the way down.", author: "Kurt Vonnegut" },
  { text: "Of all the words of mice and men, the saddest are 'It might have been.'", author: "Kurt Vonnegut" },
  { text: "Laughter is the closest distance between two people.", author: "Victor Borge" },
  { text: "The trouble with having an open mind is that people will insist on coming along and trying to put things in it.", author: "Terry Pratchett" },
  { text: "I'd rather be hated for who I am than loved for who I am not.", author: "Kurt Cobain" },
  { text: "A person is smart. People are dumb, panicky, dangerous animals.", author: "K, Men in Black" },
  { text: "With great power comes great responsibility.", author: "Voltaire / Spider-Man" },
  { text: "Why so serious?", author: "The Joker" },
  { text: "Do or do not. There is no try.", author: "Yoda" },
  { text: "May the Force be with you.", author: "Star Wars" },
  { text: "Elementary, my dear Watson.", author: "Sherlock Holmes" },
  { text: "It's dangerous to go alone! Take this.", author: "The Legend of Zelda" },
  { text: "The truth will set you free, but first it will make you miserable.", author: "James A. Garfield" },
  { text: "Be nice to nerds. Chances are you'll end up working for one.", author: "Bill Gates" },
  { text: "Never memorize something that you can look up.", author: "Albert Einstein" },
  { text: "Common sense is not so common.", author: "Voltaire" },
  { text: "In this world nothing can be said to be certain except death and taxes.", author: "Benjamin Franklin" },
  { text: "An investment in knowledge pays the best interest.", author: "Benjamin Franklin" },
  { text: "Energy and persistence conquer all things.", author: "Benjamin Franklin" },
  { text: "By failing to prepare, you are preparing to fail.", author: "Benjamin Franklin" },
  { text: "Justice will not be served until those who are unaffected are as outraged as those who are.", author: "Benjamin Franklin" },
  { text: "Our deepest fear is not that we are inadequate. Our deepest fear is that we are powerful beyond measure.", author: "Marianne Williamson" },
  { text: "The most beautiful thing we can experience is the mysterious.", author: "Albert Einstein" },
  { text: "The difference between stupidity and genius is that genius has its limits.", author: "Albert Einstein" },
  { text: "Try to become not a man of success, but try rather to become a man of value.", author: "Albert Einstein" },
  { text: "Education is what remains after one has forgotten what one has learned in school.", author: "Albert Einstein" },
  { text: "Peace cannot be kept by force; it can only be achieved by understanding.", author: "Albert Einstein" },
  { text: "God does not play dice with the universe.", author: "Albert Einstein" },
  { text: "Gravitation is not responsible for people falling in love.", author: "Albert Einstein" },
  { text: "The world as we have created it is a process of our thinking.", author: "Albert Einstein" },
  { text: "Life is like riding a bicycle. To keep your balance, you must keep moving.", author: "Albert Einstein" },
  { text: "I speak to everyone in the same way, whether he is the garbage man or the president of the university.", author: "Albert Einstein" },
  { text: "If you can't explain it to a six year old, you don't understand it yourself.", author: "Albert Einstein" },
  { text: "A clever person solves a problem. A wise person avoids it.", author: "Albert Einstein" },
  { text: "There are only two ways to live your life. One is as though nothing is a miracle.", author: "Albert Einstein" },
  { text: "The measure of intelligence is the ability to change.", author: "Albert Einstein" },
  { text: "If you want your children to be intelligent, read them fairy tales.", author: "Albert Einstein" },
  { text: "Insanity is doing the same thing over and over and expecting different results.", author: "Albert Einstein" },
  { text: "Any fool can know. The point is to understand.", author: "Albert Einstein" },
  { text: "Try not to become a man of success. Rather become a man of value.", author: "Albert Einstein" },
  { text: "The world will not be destroyed by those who do evil, but by those who watch them without doing anything.", author: "Albert Einstein" },
  { text: "Something is always born of excess: great art was born of great terrors.", author: "Anaïs Nin" },
  { text: "We write to taste life twice, in the moment and in retrospect.", author: "Anaïs Nin" },
  { text: "And the day came when the risk to remain tight in a bud was more painful than the risk it took to blossom.", author: "Anaïs Nin" },
  { text: "I must be a mermaid. I have no fear of depths and a great fear of shallow living.", author: "Anaïs Nin" },
  { text: "You cannot save people, you can only love them.", author: "Anaïs Nin" },
  { text: "How far that little candle throws its beams! So shines a good deed in a naughty world.", author: "William Shakespeare" },
  { text: "All the world's a stage, and all the men and women merely players.", author: "William Shakespeare" },
  { text: "To thine own self be true.", author: "William Shakespeare" },
  { text: "The course of true love never did run smooth.", author: "William Shakespeare" },
  { text: "Our doubts are traitors and make us lose the good we oft might win by fearing to attempt.", author: "William Shakespeare" },
  { text: "Hell is empty and all the devils are here.", author: "William Shakespeare" },
  { text: "What's done cannot be undone.", author: "William Shakespeare" },
  { text: "We know what we are, but know not what we may be.", author: "William Shakespeare" },
  { text: "The robbed that smiles, steals something from the thief.", author: "William Shakespeare" },
  { text: "Good night, good night! Parting is such sweet sorrow.", author: "William Shakespeare" },
  { text: "It is not in the stars to hold our destiny but in ourselves.", author: "William Shakespeare" },
  { text: "Give every man thy ear, but few thy voice.", author: "William Shakespeare" },
  { text: "Some are born great, some achieve greatness, and some have greatness thrust upon them.", author: "William Shakespeare" },
  { text: "This above all: to thine own self be true.", author: "William Shakespeare" },
  { text: "We are such stuff as dreams are made on.", author: "William Shakespeare" },
  { text: "What a piece of work is a man!", author: "William Shakespeare" },
  { text: "Cowards die many times before their deaths; the valiant never taste of death but once.", author: "William Shakespeare" },

  // ── Final batch
  { text: "You've got to get up every morning with determination if you're going to go to bed with satisfaction.", author: "George Lorimer" },
  { text: "Keep your face always toward the sunshine, and shadows will fall behind you.", author: "Walt Whitman" },
  { text: "The clearest way into the Universe is through a forest wilderness.", author: "John Muir" },
  { text: "In all things of nature there is something of the marvellous.", author: "Aristotle" },
  { text: "We don't stop playing because we grow old; we grow old because we stop playing.", author: "George Bernard Shaw" },
  { text: "Life isn't about finding yourself. Life is about creating yourself.", author: "George Bernard Shaw" },
  { text: "People who say it cannot be done should not interrupt those who are doing it.", author: "George Bernard Shaw" },
  { text: "A happy family is but an earlier heaven.", author: "George Bernard Shaw" },
  { text: "Better never means better for everyone. It always means worse for some.", author: "Margaret Atwood" },
  { text: "We still have time to go right, if we have the moral courage and wisdom.", author: "Jimmy Carter" },
  { text: "Returning violence for violence multiplies violence.", author: "Martin Luther King Jr." },
  { text: "Darkness cannot drive out darkness; only light can do that.", author: "Martin Luther King Jr." },
  { text: "Life's most persistent and urgent question is: What are you doing for others?", author: "Martin Luther King Jr." },
  { text: "The time is always right to do what is right.", author: "Martin Luther King Jr." },
  { text: "Faith is taking the first step even when you can't see the whole staircase.", author: "Martin Luther King Jr." },
  { text: "Our lives begin to end the day we become silent about things that matter.", author: "Martin Luther King Jr." },
  { text: "If you can't fly then run, if you can't run then walk, if you can't walk then crawl, but whatever you do you have to keep moving forward.", author: "Martin Luther King Jr." },
  { text: "Intelligence plus character — that is the goal of true education.", author: "Martin Luther King Jr." },
  { text: "I have decided to stick with love. Hate is too great a burden to bear.", author: "Martin Luther King Jr." },
  { text: "Injustice anywhere is a threat to justice everywhere.", author: "Martin Luther King Jr." },
  { text: "Never, never, never give up.", author: "Winston Churchill" },
  { text: "He who conquers himself is the mightiest warrior.", author: "Confucius" },
  { text: "The only journey is the one within.", author: "Rainer Maria Rilke" },
  { text: "Go confidently in the direction of your dreams. Live the life you've imagined.", author: "Henry David Thoreau" },
  { text: "What lies behind you and what lies in front of you, pales in comparison to what lies inside of you.", author: "Ralph Waldo Emerson" },
  { text: "The creation of something new is not accomplished by the intellect but by the play instinct.", author: "Carl Jung" },
  { text: "Who looks outside, dreams; who looks inside, awakes.", author: "Carl Jung" },
  { text: "Your vision will become clear only when you look into your heart.", author: "Carl Jung" },
  { text: "Everything that irritates us about others can lead us to an understanding of ourselves.", author: "Carl Jung" },
  { text: "You are not what happened to you; you are what you choose to become.", author: "Carl Jung" },
  { text: "The shoe that fits one person pinches another; there is no recipe for living that suits all cases.", author: "Carl Jung" },
  { text: "Knowing your own darkness is the best method for dealing with the darknesses of other people.", author: "Carl Jung" },
  { text: "The privilege of a lifetime is to become who you truly are.", author: "Carl Jung" },
  { text: "We cannot change anything unless we accept it.", author: "Carl Jung" },
  { text: "Be realistic: plan for a miracle.", author: "Osho" },
  { text: "If you love a flower, don't pick it up. Because if you pick it up it dies and it ceases to be what you love.", author: "Osho" },
  { text: "The real question is not whether life exists after death. The real question is whether you are alive before death.", author: "Osho" },
  { text: "Experience life in all possible ways — good-bad, bitter-sweet, dark-light, summer-winter.", author: "Osho" },
  { text: "To be creative means to be in love with life.", author: "Osho" },
  { text: "What you resist persists.", author: "Carl Jung" },
  { text: "The wound is the place where the Light enters you.", author: "Rumi" },
  { text: "Out beyond ideas of wrongdoing and rightdoing, there is a field. I'll meet you there.", author: "Rumi" },
  { text: "You were born with wings, why prefer to crawl through life?", author: "Rumi" },
  { text: "Let the beauty we love be what we do.", author: "Rumi" },
  { text: "Yesterday I was clever, so I wanted to change the world. Today I am wise, so I am changing myself.", author: "Rumi" },
  { text: "Raise your words, not voice. It is rain that grows flowers, not thunder.", author: "Rumi" },
  { text: "What you seek is seeking you.", author: "Rumi" },
  { text: "Don't grieve. Anything you lose comes round in another form.", author: "Rumi" },
  { text: "Silence is the language of god, all else is poor translation.", author: "Rumi" },
  { text: "These pains you feel are messengers. Listen to them.", author: "Rumi" },
  { text: "The inspiration you seek is already within you. Be silent and listen.", author: "Rumi" },
  { text: "Do not be satisfied with the stories that come before you. Unfold your own myth.", author: "Rumi" },
  { text: "Why should I be unhappy? Every parcel of my being is in full bloom.", author: "Rumi" },
  { text: "Live life as if everything is rigged in your favour.", author: "Rumi" },
  { text: "Be a lamp, or a lifeboat, or a ladder.", author: "Rumi" },
  { text: "Let yourself be silently drawn by the strange pull of what you really love.", author: "Rumi" },
  { text: "Dance until you shatter yourself.", author: "Rumi" },
  { text: "The art of knowing is knowing what to ignore.", author: "Rumi" },
  { text: "When you do things from your soul, you feel a river moving in you, a joy.", author: "Rumi" },
  { text: "Ignore those that make you fearful and sad.", author: "Rumi" },
  { text: "As you start to walk on the way, the way appears.", author: "Rumi" },
  { text: "Every object, every being, is a jar full of delight.", author: "Rumi" },
  { text: "Forget safety. Live where you fear to live.", author: "Rumi" },
];